### ISSUE TITLE
"Learn" doesn't work

### ISSUE THREAD

**Issue by chrismetzgr** [learn-co-curriculum/html-album-cover#15]
The instructions say to run learn to see if the tests are passing, but I get
"This directory doesn't appear to have any specs in it."

**Comment by sarahrivas** [comment]
I don't see the test file in the repo and I am also unable to successfully run "learn". Thanks.

**Comment by kwebster2** [comment]
@Alicekb 
It looks like the README for this lab has instructions to run tests, although there are not any tests in this repo. Additionally, there is a "light" for tests in this lab, but I believe we should just be requiring a pull request.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback, @critsmet.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
