### ISSUE TITLE
Cannot Pull the entire lesson

### ISSUE THREAD

**Issue by kerumburg** [learn-co-curriculum/html-album-cover#16]
Hi all - for some reason only only index.html is showing up in my files - how to I get all of the other files to appear so I can write the links?

![image](https://user-images.githubusercontent.com/40170637/41319560-c6724262-6ece-11e8-9dbb-33822dc42c66.png)

**Comment by maxwellbenton** [comment]
Hi @kerumburg,

Thank you for providing feedback. This lesson has been updated and should now work properly. We apologize for any frustration this caused!
