### ISSUE TITLE
No Test File

### ISSUE THREAD

**Issue by yunglleung1** [learn-co-curriculum/html-album-cover#17]
There is no test file.  I cannot run tests.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @yunglleung1.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
