### ISSUE TITLE
No method text error

### ISSUE THREAD

**Issue by margogeppert** [learn-co-curriculum/html-album-cover#19]
I wrote < p > PUBLISHED BY.. < / p >

Then I receive this feedback when I press enter learn. This is my last line that needs to be fixed, any help?

1) HTML Album Cover within <body> the back section contains the correct header sizes and text content
     Failure/Error: expect(back_cover.children.select {|ch| ch.name == "p"}.first.children.first.text).to include("PUBLISHED BY"), "The 'p' tag should include the text 'PUBLISHED BY'"

     NoMethodError:
       undefined method `text' for nil:NilClass
     # ./spec/album_cover_spec.rb:25:in `block (3 levels) in <top (required)>'

**Comment by maxwellbenton** [comment]
Hi @margogeppert,

Thank you for this feedback, and sorry that we weren't able to help. I hope you were able to get help with this issue. I was unable to reproduce your error, but we've updated this lesson's tests and checked that everything is working as expected.
