### ISSUE TITLE
Nitrous and viewing HTML locally

### ISSUE THREAD

**Issue by thegands** [learn-co-curriculum/html-album-cover#2]
It is quite cumbersome view written HTML code within the Nitrous environment compared to a local environment. Instead of making changes and downloading the project files to my local haddrive, I opted to use the gh-pages branch so I could view my changes after every push command in Nitrous. GitHub's interface makes this process fairly apparent but I was still disappointed that GitHub's page publishing feature was not covered in this lesson to make it easier for those of us developing in the Nitrous environment.

I think it would be helpful to include a quick refresh of git commands particularly pertaining to creating a new branch named gh-pages, commiting and pushing changes to the new branch, then merging the finished gh-pages branch with the master branch. This would have certainly saved me some time and confusion.

**Comment by AnnJohn** [comment]
since we no longer use Nitrous, closing this issue.

@thegands if you haven't yet already, please download our new IDE at learn.co/ide

Thanks!
