### ISSUE TITLE
No tests

### ISSUE THREAD

**Issue by bryanteng** [learn-co-curriculum/html-album-cover#20]
There are no tests to run even though it asks to run tests.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @bryanteng.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
