### ISSUE TITLE
learn command invalid - no spec file

### ISSUE THREAD

**Issue by kells08** [learn-co-curriculum/html-album-cover#22]
There isn't a spec file, so I cannot "pass" the tests. This causes the 2nd light to not turn green, and it doesn't register that I've completed this lesson.

**Comment by marycodes2** [comment]
This happened to me as well.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @kells08 and @marycodes2.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
