### ISSUE TITLE
Can't submit

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/html-album-cover#23]
The learn IDE says it has to pass local tests, but there are no spec files in the directory, so even when I run learn submit it isn't marked as complete.

**Comment by d-d-d-dalia** [comment]
This is still an issue.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @jeffcrockett.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
