### ISSUE TITLE
First Learn Lab

### ISSUE THREAD

**Issue by cwoolnough** [learn-co-curriculum/html-album-cover#24]
I don't understand where I am supposed to be doing this work? In my personal terminal or the IDE?  I started in the my own terminal, created a folder and new file but cannot pass the lab as Learn doesnt work.

**Comment by maxwellbenton** [comment]
Hi @cwoolnough,

Thank you for providing feedback. This lesson has been updated and should now work properly. We apologize for any frustration this caused!
