### ISSUE TITLE
Missing specs

### ISSUE THREAD

**Issue by cenamy** [learn-co-curriculum/html-album-cover#28]
Seems like it was raised previously but am encountering the missing specs issue again.

https://github.com/learn-co-curriculum/html-album-cover/issues/18

**Comment by maxwellbenton** [comment]
Hi @amycen,

Thank you for bringing this to our attention! It looks like there was an issue getting the updated test content to the prework version of this lab. We've made sure that the specs are showing up now. Thank you for letting us know!
