### ISSUE TITLE
Error with required gem and instructions.

### ISSUE THREAD

**Issue by snsavage** [learn-co-curriculum/html-album-cover#3]
There are two issues with this lab.  

The first is more timely.  The lab requires the green_onion gem which requires the rainbow gem.  Having there is a bug with the green_onion gem and the way that is requires rainbow.  This causes an failure/error when the rspec tests run preventing the tests from passing.

See here for more info:  https://github.com/intridea/green_onion/issues/19 and https://github.com/intridea/green_onion/pull/18

Second, the instructions should be improved for this lab.  I had to install both the green_onion gem and qt to get this to work.  There is a warning about Firefox, but not these gems.

**Comment by AnnJohn** [comment]
hi @snsavage sorry for the delay with this. We removed Green Onion testing so closing this issue.
