### ISSUE TITLE
Last test

### ISSUE THREAD

**Issue by dannyflatiron** [learn-co-curriculum/html-album-cover#30]
Test requires img src to be https://s3.amazonaws.com/learn-verified/columbia-logo.png. But it doesn't pass. Test passes with url https://s3.amazonaws.com/learn-verified/sony-logo.png

**Comment by lizbur10** [comment]
Hi there! Thank you for spotting this issue and providing feedback. The test specs have been updated to correct the error.

Thanks for contributing to the Flatiron School curriculum! 💙
