### ISSUE TITLE
"TASKS 1, 2 and 3 are no longer relevant.  The new IDE accomplishes this"

### ISSUE THREAD

**Issue by CaptRat** [learn-co-curriculum/html-album-cover#8]
![screen shot 2016-12-29 at 12 36 44 pm](https://cloud.githubusercontent.com/assets/17881768/21553080/7bed275a-cdc3-11e6-8e8d-a4bd9fe80478.jpg)

And if you remove this on HTML Album Cover, it repeats (the old design) on the Riyadh Blog post lab, (next one)

**Comment by gj** [comment]
Hi @CaptRat !

The IDE's actually not accomplishing any of those things — it's the `learn-co` gem, which also works outside of the IDE. I've added a note to the lesson: d78788d.

Thanks!
